title: Yuwei Zhang (张俞炜)
description: Peerless.
url: https://zhangyw.work

# Owner/author information
owner:
  name: Yuwei Zhang
  avatar: zhangyuwei.jpg
  email: zhangyuwei@iscas.ac.cn
  twitter: Wayne_bupt
  github: zhangyuwei-iscas
  scholar: https://scholar.google.com/citations?user=ohszaiAAAAAJ

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "Og4KBW1Mh4piS1XfFFdzkKhjofyUvibDbPNWw029Scc"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true

exclude: ["task_plan.md", "findings.md", "progress.md", "README.md"]
